name: cPanel Deploy Action
on:
  push:
    branches:
    - main
jobs:
  FTP-Deploy-Action:
    name: FTP-Deploy-Action
    runs-on: ubuntu-letest
    steps:
    - uses: action/checkout@2.1.0
      with: 
        fetch-depth: 2
    - name: FTP-Deploy-Action
      uses: SamKirkland/FTP-Deploy-Action@3.1.1
      with:
        ftp_server: ${{ secrets.FTP_SERVER }}
        ftp_username: ${{ secrets.FTP_USERNAME }}
        ftp_password: ${{ secrets.FTP_PASSWORD }}
